const GRIMOIRE_DATA = {
  herbs: [
    { name: "Lavender", correspondences: ["peace_sleep", "purification", "calm"], form: "flower", description: "Induces deep tranquility, calm slumber, and emotional balance." },
    { name: "Rosemary", correspondences: ["protection", "purification", "memory"], form: "herb", description: "Powerful all-purpose defensive botanical; cleanses and wards spaces." },
    { name: "Sage", correspondences: ["purification", "wisdom"], form: "herb", description: "Clears lingering negative energy and invites mental clarity." },
    { name: "Basil", correspondences: ["prosperity", "protection", "love"], form: "herb", description: "Draws steady wealth, financial luck, and domestic harmony." },
    { name: "Peppermint", correspondences: ["prosperity", "healing", "safe_travel"], form: "herb", description: "High-vibration botanical for rapid abundance and renewed vitality." },
    { name: "Thyme", correspondences: ["courage", "healing", "psychic_intuition"], form: "herb", description: "Dispels fear, builds internal fortitude, and enhances psychic dreams." },
    { name: "Chamomile", correspondences: ["peace_sleep", "prosperity", "luck"], form: "flower", description: "Solar flower used to soothe stress and attract gentle wealth." },
    { name: "Cinnamon", correspondences: ["prosperity", "passion", "courage"], form: "bark", description: "Accelerates spell speed, adding heat, drive, and rapid financial luck." },
    { name: "Bay Leaf", correspondences: ["wishes", "protection", "prosperity"], form: "whole_leaf", description: "Traditional talisman for manifesting written intentions and boundary warding." },
    { name: "Rose Petals", correspondences: ["love", "beauty", "healing"], form: "flower", description: "Attracts unconditional affection, self-worth, and emotional restoration." },
    { name: "Jasmine Flower", correspondences: ["love", "psychic_intuition", "prosperity"], form: "flower", description: "Lunar flower associated with spiritual romance and intuitive dreams." },
    { name: "Lemon Balm", correspondences: ["healing", "love", "peace_sleep"], form: "herb", description: "Restores vitality, lifts melancholic moods, and dispels tension." },
    { name: "Yarrow", correspondences: ["courage", "love", "psychic_intuition"], form: "flower", description: "Ancient boundary herb; binds love connections and protects against energetic drain." },
    { name: "Calendula", correspondences: ["joy", "protection", "legal_matters"], form: "flower", description: "Brings radiant solar light, legal success, and optimistic vitality." },
    { name: "Lemongrass", correspondences: ["purification", "psychic_intuition"], form: "herb", description: "Cuts through energetic fog and sharpens divination faculties." },
    { name: "Clove", correspondences: ["protection", "prosperity", "banishing"], form: "spice", description: "Drives away gossip and malevolent intent while guarding wealth." },
    { name: "Dill", correspondences: ["protection", "prosperity", "luck"], form: "seed", description: "Shields against unwanted intrusions and preserves material gains." },
    { name: "Fennel Seed", correspondences: ["protection", "purification", "longevity"], form: "seed", description: "Cleanses stale energetic buildup and guards spiritual longevity." },
    { name: "Hyssop", correspondences: ["purification", "protection"], form: "herb", description: "Sacred cleansing botanical for absolute spiritual purification." },
    { name: "Marjoram", correspondences: ["happiness", "protection", "healing"], form: "herb", description: "Promotes home peace, familial joy, and gentle protection." },
    { name: "Nettle", correspondences: ["protection", "banishing", "healing"], form: "herb", description: "Fierce warding herb that reflects negative energy back to its source." },
    { name: "Vervain", correspondences: ["protection", "love", "purification"], form: "herb", description: "Ancient folk catalyst that amplifies accompanying botanical energies." },
    { name: "Mugwort", correspondences: ["psychic_intuition", "protection", "peace_sleep"], form: "herb", description: "Awakens the third eye and guards astral travel during rest." },
    { name: "Dandelion", correspondences: ["wishes", "psychic_intuition"], form: "root_flower", description: "Carries prayers and deep desires to the spiritual plane." },
    { name: "Elder Flower", correspondences: ["protection", "prosperity", "healing"], form: "flower", description: "Connects with woodland lore for deep shielding and blessing." },
    { name: "Hibiscus", correspondences: ["love", "passion", "psychic_intuition"], form: "flower", description: "Ignites romance, sensual attraction, and passionate willpower." },
    { name: "Comfrey Leaf", correspondences: ["safe_travel", "prosperity", "healing"], form: "herb", description: "Guards luggage and travelers; repairs fragmented energy." },
    { name: "St. John's Wort", correspondences: ["protection", "courage", "happiness"], form: "herb", description: "Solar talisman against darkness, nightmares, and despair." },
    { name: "Lilac", correspondences: ["protection", "memory"], form: "flower", description: "Soft spiritual barrier that preserves sacred memories." },
    { name: "Patchouli Leaf", correspondences: ["prosperity", "grounding", "passion"], form: "herb", description: "Rich, earthy botanical for anchoring money and physical manifestion." }
  ],
  minerals: [
    { name: "Clear Quartz", type: "crystal", correspondences: ["amplification", "clarity", "purification"], form: "point_chip", description: "Universal amplifier; magnifies the intention of every neighboring ingredient." },
    { name: "Rose Quartz", type: "crystal", correspondences: ["love", "healing", "calm"], form: "chip", description: "Softens emotional tension and broadcasts gentle romantic energy." },
    { name: "Black Tourmaline", type: "crystal", correspondences: ["protection", "grounding", "banishing"], form: "chunk", description: "Premier energetic shield; absorbs and grounds heavy or harmful vibrations." },
    { name: "Citrine", type: "crystal", correspondences: ["prosperity", "courage", "joy"], form: "chip", description: "Solar abundance stone that continually attracts success and opportunities." },
    { name: "Amethyst", type: "crystal", correspondences: ["psychic_intuition", "protection", "peace_sleep"], form: "cluster_chip", description: "Spiritual sentinel; quiets overactive minds and guards against psychic attack." },
    { name: "Tiger's Eye", type: "crystal", correspondences: ["courage", "luck", "protection"], form: "chip", description: "Sharpens focus, protects personal boundaries, and brings luck." },
    { name: "Hematite", type: "crystal", correspondences: ["grounding", "protection", "banishing"], form: "tumbled", description: "Reflective grounding stone; anchors root energy and deflects negativity." },
    { name: "Selenite", type: "crystal", correspondences: ["purification", "clarity", "amplification"], form: "wand_chip", description: "Self-cleansing crystal that maintains energetic hygiene within the vessel." },
    { name: "Pyrite", type: "mineral", correspondences: ["prosperity", "luck", "courage"], form: "cluster", description: "Gold-hued mineral that acts as an energetic magnet for wealth and bold action." },
    { name: "Carnelian", type: "crystal", correspondences: ["passion", "courage", "creativity"], form: "tumbled", description: "Ignites passion, bold self-expression, and vital creative drive." },
    { name: "Frankincense", type: "resin", correspondences: ["purification", "protection", "psychic_intuition"], form: "resin_tears", description: "Sacred resin tears that elevate vibrational frequencies." },
    { name: "Myrrh", type: "resin", correspondences: ["healing", "protection", "banishing"], form: "resin_tears", description: "Ancient restorative resin for grounding and warding." },
    { name: "Dragon's Blood", type: "resin", correspondences: ["protection", "passion", "amplification"], form: "resin_powder", description: "Potent crimson resin that drastically boosts the potency of defensive workings." },
    { name: "Copal", type: "resin", correspondences: ["purification", "clarity"], form: "resin_tears", description: "Bright, fragrant resin that purifies the aura and cleanses tools." },
    { name: "Sea Salt", type: "mineral", correspondences: ["purification", "protection", "grounding"], form: "granular_base", description: "Essential foundation layer for casting wards and anchoring intention." }
  ],
  waxColors: [
    { color: "Black", correspondences: ["protection", "banishing", "grounding"], hex: "#1c1b1a", description: "Seals out external interference, binds wards, and dispels toxicity." },
    { color: "Gold", correspondences: ["prosperity", "courage", "wishes"], hex: "#d4af37", description: "Channels solar vitality, regal abundance, and rapid success." },
    { color: "Green", correspondences: ["prosperity", "healing"], hex: "#2e5a36", description: "Anchors earthly abundance, physical recovery, and steady growth." },
    { color: "Red", correspondences: ["passion", "courage"], hex: "#8a2424", description: "Infuses fiery drive, romantic attraction, and swift energetic action." },
    { color: "White", correspondences: ["purification", "peace_sleep", "clarity"], hex: "#e8e2cf", description: "Universal sealing color for peace, spiritual alignment, and purity." },
    { color: "Purple", correspondences: ["psychic_intuition", "wisdom"], hex: "#4a2a68", description: "Deepens divination, astral perception, and spiritual authority." },
    { color: "Blue", correspondences: ["peace_sleep", "healing", "calm"], hex: "#2b4c6f", description: "Soothes internal turbulence, invites restful sleep, and speeds recovery." }
  ]
};
